In [1]:
#! usr/bin/env/python3
#-*- coding: utf-8 -*-

In [2]:
# from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import seaborn as sns
import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt

sns.set()

# plt.rc('font',family='AppleGothic')

In [3]:
# Dataframe 전체 출력 함수
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

In [4]:
data = pd.DataFrame.from_csv("name_and_train_simple_preprocess.csv")
data.head()

Name  Cat  Dog  Intact Female  Intact Male  Neutered Male  Spayed Female  \
0     1    0    1              0            0              1              0   
1     1    1    0              0            0              0              1   
2     1    0    1              0            0              1              0   
3     0    1    0              0            1              0              0   
4     0    0    1              0            0              1              0   

   OutcomeType_label  
0                  3  
1                  2  
2                  0  
3                  4  
4                  4

In [5]:
X = data[['Name', 'Cat', 'Dog', 'Intact Female',
         'Intact Male', 'Neutered Male','Spayed Female']]

print(X.head())

   Name  Cat  Dog  Intact Female  Intact Male  Neutered Male  Spayed Female
0     1    0    1              0            0              1              0
1     1    1    0              0            0              0              1
2     1    0    1              0            0              1              0
3     0    1    0              0            1              0              0
4     0    0    1              0            0              1              0


In [6]:
y = data['OutcomeType_label']
y.head()

0    3
1    2
2    0
3    4
4    4
Name: OutcomeType_label, dtype: int64

In the multiclass case, the training algorithm uses the one-vs-rest (OvR) scheme if the ‘multi_class’ option is set to ‘ovr’ and uses the cross-entropy loss, if the ‘multi_class’ option is set to ‘multinomial’

In [7]:
clf = RandomForestClassifier(
    n_estimators=100, criterion='entropy', max_depth=None,
    min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None,
    bootstrap=True, oob_score=False,
    n_jobs=1, random_state=None, verbose=0, warm_start=False, class_weight="balanced")

model_rand_forest = RandomForestClassifier.fit(clf, X, y)
train_predict = model_rand_forest.predict(X)
train_predict_proba = model_rand_forest.predict_proba(X)

train_score = model_rand_forest.score(X, y)
print("score : ", train_score)

score :  0.389838751917


In [8]:
# np.set_printoptions(threshold=np.nan)
print(train_predict)
print(train_predict_proba)

[3 0 3 ..., 3 1 1]
[[ 0.26403869  0.04660441  0.14707666  0.42803838  0.11424186]
 [ 0.51211227  0.0920665   0.08193061  0.12644637  0.18744426]
 [ 0.26403869  0.04660441  0.14707666  0.42803838  0.11424186]
 ..., 
 [ 0.26403869  0.04660441  0.14707666  0.42803838  0.11424186]
 [ 0.00065587  0.4131946   0.29341559  0.00142061  0.29131333]
 [ 0.00065587  0.4131946   0.29341559  0.00142061  0.29131333]]


In [9]:
raw_test_data = pd.DataFrame.from_csv("test.csv", index_col=False)
test_data = pd.DataFrame.from_csv("test_simple_preprocess.csv")
raw_test_data.head()

ID      Name             DateTime AnimalType SexuponOutcome AgeuponOutcome  \
0   1    Summer  2015-10-12 12:15:00        Dog  Intact Female      10 months   
1   2  Cheyenne  2014-07-26 17:59:00        Dog  Spayed Female        2 years   
2   3       Gus  2016-01-13 12:20:00        Cat  Neutered Male         1 year   
3   4     Pongo  2013-12-28 18:12:00        Dog    Intact Male       4 months   
4   5   Skooter  2015-09-24 17:59:00        Dog  Neutered Male        2 years   

                            Breed        Color  
0          Labrador Retriever Mix    Red/White  
1  German Shepherd/Siberian Husky    Black/Tan  
2          Domestic Shorthair Mix  Brown Tabby  
3               Collie Smooth Mix     Tricolor  
4            Miniature Poodle Mix        White

In [10]:
train_predict = model_rand_forest.predict(test_data)
train_predict_proba = model_rand_forest.predict_proba(test_data)

result_df = pd.concat(
    [
        raw_test_data['ID'],
        pd.DataFrame(
            train_predict_proba,
            columns=['Adoption','Died','Euthanasia','Return_to_owner','Transfer']
        )
    ], axis=1
)
result_df.to_csv("randomforest_2feature.csv")